[package]
name = "juno-stable"
version = "0.1.0"
authors = ["Ho Ba Nguyen <expertdicer@gmail.com>"]
edition = "2021"
description = "Commom types and queriers"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw20 = { version = "0.10.0" }
cosmwasm-std = { version = "1.0", features = ["iterator"] }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-storage-plus = {version = "0.13.4", features = ['iterator']}

[dev-dependencies]
cosmwasm-schema = "1.0"